### ISSUE TITLE
Criar pedidos com cartão inválido

### ISSUE THREAD

**Issue by cfgalvani** [rafaelpatro/Quack_Cielo#5]
Gostaria de saber se o módulo está funcionando certinho tanto para crédito quanto débito. Queria saber também se o módulo verifica se o cartão é válido (se tem crédito disponível, se não há algum bloqueio e esse tipo de erro) antes de criar o pedido no Magento, ou se ele permite que o pedido seja criado mesmo quando o cartão não passa. Obrigado!

**Comment by rafaelpatro** [comment]
Olá @cfgalvani 
Sim, tanto crédito quanto débito funcionam de acordo com o manual:
[Cielo-E-commerce-Manual-do-Desenvolvedor-WebService-PT-V2.5.4.pdf](https://github.com/rafaelpatro/Quack_Cielo/files/1043371/Cielo-E-commerce-Manual-do-Desenvolvedor-WebService-PT-V2.5.4.pdf)
Recomendo a leitura do manual, para entender as funcionalidades disponibilizadas pela Cielo.

Alguns recursos como _token_ e _avs_ não foram implementados. Sinta-se a vontade para contribuir.

**Comment by rafaelpatro** [comment]
Nas configurações do módulo é possível optar entre as ações abaixo.

Ações disponíveis para pagamento:

Pedido
* Registra a transação sem sensibilizar o cartão do cliente. O lojista pode realizar a transação posteriormente, sem a intervenção do cliente.
* _O pedido não é criado, caso o cartão seja inválido_

Apenas Autorizar
* Autoriza o desconto no cartão do cliente. Nesta situação o cliente já pode ver o lançamento futuro no extrato. Mas o lojista ainda tem 5 dias para aceitar ou recusar a transação.
* _O pedido não é criado, caso o cartão seja inválido, ou caso o cartão não possua saldo._

Capturar e Autorizar
* Autoriza o desconto no cartão do cliente, e captura o valor.
* _O pedido não é criado, caso o cartão seja inválido, ou caso o cartão não possua saldo._

É possível escolher a forma de autorização (com ou sem autenticação).

**Comment by cfgalvani** [comment]
Muito obrigado Rafael! Farei sim o possível para contribuir. Sucesso!
